shared: &shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mongo_path: <%= ENV["MONGO_PATH"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
production:
  <<: *shared
development:
  <<: *shared
test:
  <<: *shared
